// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // instrui o Prisma a procurar o esquema dentro da pasta prisma 
  // e não dentro do arquivo schema.prisma
  schema: 'prisma/schema',
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
